#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v18
# autospec commit: f35655a
#
# Source0 file verified with key 0xBB463350D6EF31EF (heiko@shruuf.de)
#
Name     : kpimtextedit
Version  : 24.08.0
Release  : 73
URL      : https://download.kde.org/stable/release-service/24.08.0/src/kpimtextedit-24.08.0.tar.xz
Source0  : https://download.kde.org/stable/release-service/24.08.0/src/kpimtextedit-24.08.0.tar.xz
Source1  : https://download.kde.org/stable/release-service/24.08.0/src/kpimtextedit-24.08.0.tar.xz.sig
Source2  : BB463350D6EF31EF.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause CC0-1.0 GPL-2.0 GPL-3.0 LGPL-2.0 LGPL-2.1 LGPL-3.0
Requires: kpimtextedit-data = %{version}-%{release}
Requires: kpimtextedit-lib = %{version}-%{release}
Requires: kpimtextedit-license = %{version}-%{release}
Requires: kpimtextedit-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : gnupg
BuildRequires : ktextaddons-dev
BuildRequires : qt6base-dev
BuildRequires : syntax-highlighting-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Analyzing Build Performance
For debug build time:
We need ClangBuildAnalyzer
git clone https://github.com/aras-p/ClangBuildAnalyzer
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=<path> ../
make install

%package data
Summary: data components for the kpimtextedit package.
Group: Data

%description data
data components for the kpimtextedit package.


%package dev
Summary: dev components for the kpimtextedit package.
Group: Development
Requires: kpimtextedit-lib = %{version}-%{release}
Requires: kpimtextedit-data = %{version}-%{release}
Provides: kpimtextedit-devel = %{version}-%{release}
Requires: kpimtextedit = %{version}-%{release}

%description dev
dev components for the kpimtextedit package.


%package lib
Summary: lib components for the kpimtextedit package.
Group: Libraries
Requires: kpimtextedit-data = %{version}-%{release}
Requires: kpimtextedit-license = %{version}-%{release}

%description lib
lib components for the kpimtextedit package.


%package license
Summary: license components for the kpimtextedit package.
Group: Default

%description license
license components for the kpimtextedit package.


%package locales
Summary: locales components for the kpimtextedit package.
Group: Default

%description locales
locales components for the kpimtextedit package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) BB463350D6EF31EF' gpg.status
%setup -q -n kpimtextedit-24.08.0
cd %{_builddir}/kpimtextedit-24.08.0
pushd ..
cp -a kpimtextedit-24.08.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1724638558
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DQT_MAJOR_VERSION=6  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DQT_MAJOR_VERSION=6  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1724638558
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kpimtextedit
cp %{_builddir}/kpimtextedit-%{version}/.krazy.license %{buildroot}/usr/share/package-licenses/kpimtextedit/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4 || :
cp %{_builddir}/kpimtextedit-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/kpimtextedit/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c || :
cp %{_builddir}/kpimtextedit-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/kpimtextedit/8287b608d3fa40ef401339fd907ca1260c964123 || :
cp %{_builddir}/kpimtextedit-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/kpimtextedit/2a638514c87c4923c0570c55822620fad56f2a33 || :
cp %{_builddir}/kpimtextedit-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/kpimtextedit/6091db0aead0d90182b93d3c0d09ba93d188f907 || :
cp %{_builddir}/kpimtextedit-%{version}/LICENSES/LGPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/kpimtextedit/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/kpimtextedit-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kpimtextedit/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/kpimtextedit-%{version}/LICENSES/LGPL-2.1-or-later.txt %{buildroot}/usr/share/package-licenses/kpimtextedit/6f1f675aa5f6a2bbaa573b8343044b166be28399 || :
cp %{_builddir}/kpimtextedit-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/kpimtextedit/757b86330df80f81143d5916b3e92b4bcb1b1890 || :
cp %{_builddir}/kpimtextedit-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/kpimtextedit/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/kpimtextedit-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/kpimtextedit/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/kpimtextedit-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/kpimtextedit/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/kpimtextedit-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/kpimtextedit/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/kpimtextedit-%{version}/metainfo.yaml.license %{buildroot}/usr/share/package-licenses/kpimtextedit/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
%find_lang libkpimtextedit6
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/qlogging-categories6/kpimtextedit.categories

%files dev
%defattr(-,root,root,-)
/usr/include/KPim6/KPIMTextEdit/KPIMTextEdit/AbstractMarkupBuilder
/usr/include/KPim6/KPIMTextEdit/KPIMTextEdit/MarkupDirector
/usr/include/KPim6/KPIMTextEdit/KPIMTextEdit/PlainTextMarkupBuilder
/usr/include/KPim6/KPIMTextEdit/KPIMTextEdit/RichTextComposer
/usr/include/KPim6/KPIMTextEdit/KPIMTextEdit/RichTextComposerActions
/usr/include/KPim6/KPIMTextEdit/KPIMTextEdit/RichTextComposerControler
/usr/include/KPim6/KPIMTextEdit/KPIMTextEdit/RichTextComposerEmailQuoteHighlighter
/usr/include/KPim6/KPIMTextEdit/KPIMTextEdit/RichTextComposerImages
/usr/include/KPim6/KPIMTextEdit/KPIMTextEdit/RichTextComposerWidget
/usr/include/KPim6/KPIMTextEdit/KPIMTextEdit/RichTextExternalComposer
/usr/include/KPim6/KPIMTextEdit/KPIMTextEdit/TextHTMLBuilder
/usr/include/KPim6/KPIMTextEdit/KPIMTextEdit/TextUtils
/usr/include/KPim6/KPIMTextEdit/kpimtextedit/abstractmarkupbuilder.h
/usr/include/KPim6/KPIMTextEdit/kpimtextedit/kpimtextedit_export.h
/usr/include/KPim6/KPIMTextEdit/kpimtextedit/markupdirector.h
/usr/include/KPim6/KPIMTextEdit/kpimtextedit/plaintextmarkupbuilder.h
/usr/include/KPim6/KPIMTextEdit/kpimtextedit/richtextcomposer.h
/usr/include/KPim6/KPIMTextEdit/kpimtextedit/richtextcomposeractions.h
/usr/include/KPim6/KPIMTextEdit/kpimtextedit/richtextcomposercontroler.h
/usr/include/KPim6/KPIMTextEdit/kpimtextedit/richtextcomposeremailquotehighlighter.h
/usr/include/KPim6/KPIMTextEdit/kpimtextedit/richtextcomposerimages.h
/usr/include/KPim6/KPIMTextEdit/kpimtextedit/richtextcomposerwidget.h
/usr/include/KPim6/KPIMTextEdit/kpimtextedit/richtextexternalcomposer.h
/usr/include/KPim6/KPIMTextEdit/kpimtextedit/texthtmlbuilder.h
/usr/include/KPim6/KPIMTextEdit/kpimtextedit/textutils.h
/usr/include/KPim6/KPIMTextEdit/kpimtextedit_version.h
/usr/lib64/cmake/KPim6TextEdit/KPim6TextEditConfig.cmake
/usr/lib64/cmake/KPim6TextEdit/KPim6TextEditConfigVersion.cmake
/usr/lib64/cmake/KPim6TextEdit/KPim6TextEditTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KPim6TextEdit/KPim6TextEditTargets.cmake
/usr/lib64/libKPim6TextEdit.so

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libKPim6TextEdit.so.6.2.0
/usr/lib64/libKPim6TextEdit.so.6
/usr/lib64/libKPim6TextEdit.so.6.2.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kpimtextedit/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/kpimtextedit/2a638514c87c4923c0570c55822620fad56f2a33
/usr/share/package-licenses/kpimtextedit/6091db0aead0d90182b93d3c0d09ba93d188f907
/usr/share/package-licenses/kpimtextedit/6f1f675aa5f6a2bbaa573b8343044b166be28399
/usr/share/package-licenses/kpimtextedit/757b86330df80f81143d5916b3e92b4bcb1b1890
/usr/share/package-licenses/kpimtextedit/7d9831e05094ce723947d729c2a46a09d6e90275
/usr/share/package-licenses/kpimtextedit/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4
/usr/share/package-licenses/kpimtextedit/8287b608d3fa40ef401339fd907ca1260c964123
/usr/share/package-licenses/kpimtextedit/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
/usr/share/package-licenses/kpimtextedit/e458941548e0864907e654fa2e192844ae90fc32

%files locales -f libkpimtextedit6.lang
%defattr(-,root,root,-)

