#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : kpimtextedit
Version  : 19.08.1
Release  : 13
URL      : https://download.kde.org/stable/applications/19.08.1/src/kpimtextedit-19.08.1.tar.xz
Source0  : https://download.kde.org/stable/applications/19.08.1/src/kpimtextedit-19.08.1.tar.xz
Source1 : https://download.kde.org/stable/applications/19.08.1/src/kpimtextedit-19.08.1.tar.xz.sig
Summary  : A textedit with PIM-specific features
Group    : Development/Tools
License  : LGPL-2.1
Requires: kpimtextedit-data = %{version}-%{release}
Requires: kpimtextedit-lib = %{version}-%{release}
Requires: kpimtextedit-license = %{version}-%{release}
Requires: kpimtextedit-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : grantlee-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : syntax-highlighting-dev

%description
No detailed description available

%package data
Summary: data components for the kpimtextedit package.
Group: Data

%description data
data components for the kpimtextedit package.


%package dev
Summary: dev components for the kpimtextedit package.
Group: Development
Requires: kpimtextedit-lib = %{version}-%{release}
Requires: kpimtextedit-data = %{version}-%{release}
Provides: kpimtextedit-devel = %{version}-%{release}
Requires: kpimtextedit = %{version}-%{release}
Requires: kpimtextedit = %{version}-%{release}

%description dev
dev components for the kpimtextedit package.


%package lib
Summary: lib components for the kpimtextedit package.
Group: Libraries
Requires: kpimtextedit-data = %{version}-%{release}
Requires: kpimtextedit-license = %{version}-%{release}

%description lib
lib components for the kpimtextedit package.


%package license
Summary: license components for the kpimtextedit package.
Group: Default

%description license
license components for the kpimtextedit package.


%package locales
Summary: locales components for the kpimtextedit package.
Group: Default

%description locales
locales components for the kpimtextedit package.


%prep
%setup -q -n kpimtextedit-19.08.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567708519
mkdir -p clr-build
pushd clr-build
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1567708519
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kpimtextedit
cp COPYING.LIB %{buildroot}/usr/share/package-licenses/kpimtextedit/COPYING.LIB
pushd clr-build
%make_install
popd
%find_lang libkpimtextedit

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/qlogging-categories5/kpimtextedit.categories

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/AbstractTextToSpeechInterface
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/EditorUtil
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/EmoticonUnicodeTab
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/PlainTextEditFindBar
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/PlainTextEditor
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/PlainTextEditorWidget
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/PlainTextSyntaxSpellCheckingHighlighter
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/RichTextComposer
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/RichTextComposerActions
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/RichTextComposerControler
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/RichTextComposerEmailQuoteHighlighter
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/RichTextComposerImages
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/RichTextComposerWidget
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/RichTextEditor
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/RichTextEditorWidget
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/RichTextExternalComposer
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/SelectSpecialCharDialog
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/SlideContainer
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/TextEditFindBarBase
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/TextEditorCompleter
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/TextGotoLineWidget
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/TextToSpeech
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/TextToSpeechActions
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/TextToSpeechInterface
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/TextToSpeechWidget
/usr/include/KF5/KPIMTextEdit/KPIMTextEdit/TextUtils
/usr/include/KF5/KPIMTextEdit/kpimtextedit/abstracttexttospeechinterface.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/editorutil.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/emoticonunicodetab.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/kpimtextedit_export.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/plaintexteditfindbar.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/plaintexteditor.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/plaintexteditorwidget.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/plaintextsyntaxspellcheckinghighlighter.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/richtextcomposer.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/richtextcomposeractions.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/richtextcomposercontroler.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/richtextcomposeremailquotehighlighter.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/richtextcomposerimages.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/richtextcomposerwidget.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/richtexteditor.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/richtexteditorwidget.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/richtextexternalcomposer.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/selectspecialchardialog.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/slidecontainer.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/texteditfindbarbase.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/texteditorcompleter.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/textgotolinewidget.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/texttospeech.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/texttospeechactions.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/texttospeechinterface.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/texttospeechwidget.h
/usr/include/KF5/KPIMTextEdit/kpimtextedit/textutils.h
/usr/include/KF5/kpimtextedit_version.h
/usr/lib64/cmake/KF5PimTextEdit/KF5PimTextEditConfig.cmake
/usr/lib64/cmake/KF5PimTextEdit/KF5PimTextEditConfigVersion.cmake
/usr/lib64/cmake/KF5PimTextEdit/KF5PimTextEditTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5PimTextEdit/KF5PimTextEditTargets.cmake
/usr/lib64/libKF5PimTextEdit.so
/usr/lib64/qt5/mkspecs/modules/qt_KPIMTextEdit.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5PimTextEdit.so.5
/usr/lib64/libKF5PimTextEdit.so.5.12.1
/usr/lib64/qt5/plugins/designer/kpimtexteditwidgets.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kpimtextedit/COPYING.LIB

%files locales -f libkpimtextedit.lang
%defattr(-,root,root,-)

